name: text
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: Fruktur
      fonts:
      - asset: Assets/Fonts/Fruktur/Fruktur-Italic.ttf
    - family: Fruktur[1]
      fonts:
      - asset: Assets/Fonts/Fruktur/Fruktur-Regular.ttf

